package com.fcant.mybatis.ch01.bean;

public class Card {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.cid
     *
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.balance
     *
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    private Integer balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_card.suid
     *
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    private Integer suid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.cid
     *
     * @return the value of t_card.cid
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.cid
     *
     * @param cid the value for t_card.cid
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.balance
     *
     * @return the value of t_card.balance
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.balance
     *
     * @param balance the value for t_card.balance
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_card.suid
     *
     * @return the value of t_card.suid
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    public Integer getSuid() {
        return suid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_card.suid
     *
     * @param suid the value for t_card.suid
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    public void setSuid(Integer suid) {
        this.suid = suid;
    }
}