package com.fcant.mybatis.ch01.bean;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.cid
     *
     * @mbg.generated Tue Jun 11 16:29:36 GMT+08:00 2019
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.cname
     *
     * @mbg.generated Tue Jun 11 16:29:36 GMT+08:00 2019
     */
    private String cname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.cid
     *
     * @return the value of t_course.cid
     * @mbg.generated Tue Jun 11 16:29:36 GMT+08:00 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.cid
     *
     * @param cid the value for t_course.cid
     * @mbg.generated Tue Jun 11 16:29:36 GMT+08:00 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.cname
     *
     * @return the value of t_course.cname
     * @mbg.generated Tue Jun 11 16:29:36 GMT+08:00 2019
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.cname
     *
     * @param cname the value for t_course.cname
     * @mbg.generated Tue Jun 11 16:29:36 GMT+08:00 2019
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }
}