package com.fcant.mybatis.ch01.mapper;

import com.fcant.mybatis.ch01.bean.Card;
import com.fcant.mybatis.ch01.bean.CardExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    long countByExample(CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    int deleteByExample(CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    int insert(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    int insertSelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    List<Card> selectByExample(CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    Card selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Card record, @Param("example") CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Card record, @Param("example") CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_card
     *
     * @mbg.generated Mon Jun 10 18:48:24 GMT+08:00 2019
     */
    int updateByPrimaryKey(Card record);
}